language: node_js

node_js:
  - 11

stages:
  - build
  - test
  - release

jobs:
  include:
    - stage: build
      before_script: yarn
      skip_cleanup: true
      script:
        - yarn build

    - stage: test
      before_script: yarn
      skip_cleanup: true
      script:
        - yarn test

    - stage: release
      before_script: yarn
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
