language: node_js

node_js:
  - 11

stages:
  - build
  - test
  - release

jobs:
  include:
    - stage: test
      before_script: yarn && yarn build
      script:
        - yarn test
      deploy:
        provider: script
        skip_cleanup: true
        script:
          # - npx semantic-release
          - echo 'Deploying!'
